complexity:
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 10
  ComplexCondition:
    active: true
    allowedConditions: 4
  LongMethod:
    active: true
    allowedLines: 60
  LongParameterList:
    active: true
    allowedFunctionParameters: 6
    allowedConstructorParameters: 8
  TooManyFunctions:
    active: true
    allowedFunctionsPerClass: 15

comments:
  UndocumentedPublicClass:
    active: true
    excludes: ["**/test/**"]
    searchInInnerObject: false
  UndocumentedPublicFunction:
    active: true
    excludes: ["**/test/**"]

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  ReturnCount:
    active: true
    max: 3
